engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - src/components/**/*
exclude_paths:
- "**tests/**"
- lib/**/*
