language: node_js

cache:
  directories:
    - "node_modules"

node_js:
  - "6"

script:
  - npm run test
  - npm run test:coverage
  - npm run build

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
